# Generated by Django 3.2.6 on 2021-08-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_genre_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movies.movie'),
            preserve_default=False,
        ),
    ]
